/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as SupportRequestRouteImport } from './routes/support-request'
import { Route as ManualRouteImport } from './routes/manual'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiPublicSupportRequestNotifyRouteImport } from './routes/api/public/support-request-notify'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRequestRoute = SupportRequestRouteImport.update({
  id: '/support-request',
  path: '/support-request',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualRoute = ManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSupportRequestNotifyRoute =
  ApiPublicSupportRequestNotifyRouteImport.update({
    id: '/api/public/support-request-notify',
    path: '/api/public/support-request-notify',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/manual': typeof ManualRoute
  '/support-request': typeof SupportRequestRoute
  '/videos': typeof VideosRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/support-request-notify': typeof ApiPublicSupportRequestNotifyRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/manual': typeof ManualRoute
  '/support-request': typeof SupportRequestRoute
  '/videos': typeof VideosRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/support-request-notify': typeof ApiPublicSupportRequestNotifyRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/manual': typeof ManualRoute
  '/support-request': typeof SupportRequestRoute
  '/videos': typeof VideosRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/support-request-notify': typeof ApiPublicSupportRequestNotifyRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/manual'
    | '/support-request'
    | '/videos'
    | '/api/chat'
    | '/api/public/support-request-notify'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/manual'
    | '/support-request'
    | '/videos'
    | '/api/chat'
    | '/api/public/support-request-notify'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/manual'
    | '/support-request'
    | '/videos'
    | '/api/chat'
    | '/api/public/support-request-notify'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ManualRoute: typeof ManualRoute
  SupportRequestRoute: typeof SupportRequestRoute
  VideosRoute: typeof VideosRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPublicSupportRequestNotifyRoute: typeof ApiPublicSupportRequestNotifyRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support-request': {
      id: '/support-request'
      path: '/support-request'
      fullPath: '/support-request'
      preLoaderRoute: typeof SupportRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual': {
      id: '/manual'
      path: '/manual'
      fullPath: '/manual'
      preLoaderRoute: typeof ManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/support-request-notify': {
      id: '/api/public/support-request-notify'
      path: '/api/public/support-request-notify'
      fullPath: '/api/public/support-request-notify'
      preLoaderRoute: typeof ApiPublicSupportRequestNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ManualRoute: ManualRoute,
  SupportRequestRoute: SupportRequestRoute,
  VideosRoute: VideosRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPublicSupportRequestNotifyRoute: ApiPublicSupportRequestNotifyRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
